"""
Django settings for projet project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_42oe4&wkls(d-f^_x+u#27sob6b(@tdkj#p+-aofkf6!9nc89'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DHT',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/mysite',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
import os
STATIC_URL = "/static/"

if not DEBUG:
    STATIC_ROOT = BASE_DIR / "staticfiles"

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os

from django.core.mail import send_mail

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "imanejennane23@gmail.com"
EMAIL_HOST_PASSWORD = "jscn tokw wric lwkj"

TELEGRAM_BOT_TOKEN = "8559176194:AAF4tF3s7kSeyKjulNhkX0DsQlwAX4qCteM" # ← token
TELEGRAM_CHAT_ID = "5468593557" # ← id utilisateur/groupe

TWILIO_ACCOUNT_SID = "AC1f93399fc0e24ce16cd7f20dee3a45c1"
TWILIO_AUTH_TOKEN = "333df877ed2390925bf283bfe0b744c2"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"  # Twilio sandbox number
TWILIO_WHATSAPP_TO = "whatsapp:+212624628677"  # your phone number with country code

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}
# MQTT Broker Configuration
MQTT_BROKER = "broker.hivemq.com"  # Public broker (change for production)
# MQTT_BROKER = "localhost"  # For local Mosquitto broker
MQTT_PORT = 1883
MQTT_CLIENT_ID = "django_dht11_iot_client"

# MQTT Topics
MQTT_TOPIC_SUBSCRIBE = "dht11/sensors"  # Topic to receive sensor data
MQTT_TOPIC_PUBLISH = "dht11/alerts"     # Topic to publish alerts

# Optional: MQTT Authentication (uncomment if broker requires auth)
# MQTT_USERNAME = "your_username"
# MQTT_PASSWORD = "your_password"

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ==================== NTFY.SH PUSH NOTIFICATIONS ====================
# Enable/disable ntfy notifications
NTFY_ENABLED = True  # Set to False to disable

# Multiple users - uncomment this for multiple recipients
NTFY_TOPICS = [
    'alarm_projet_iot_',  # First person's unique topic
    #'temp_alarm_user2_unique_abc',  # Second person's unique topic
]

# Instructions for users:
# 1. Install ntfy app on your phone (iOS/Android)
# 2. Subscribe to your unique topic (e.g., 'temp_alarm_user1_unique_xyz')
# 3. Enable notifications in your phone settings
# 4. Test by sending: curl -d "test" ntfy.sh/your_topic_name