# Generated by Django 5.2.7 on 2025-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_incident_archiveincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='nom_op1',
            field=models.CharField(default='Opération Corrective 1', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='nom_op2',
            field=models.CharField(default='Opération Corrective 2', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='nom_op3',
            field=models.CharField(default='Opération Corrective 3', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op1_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op2_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op3_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
