# Generated by Django 5.2.7 on 2025-12-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_incident_nom_op1_incident_nom_op2_incident_nom_op3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='last_increment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
