# Generated by Django 5.2.7 on 2025-12-16 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incident_last_increment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveincident',
            options={'ordering': ['-date_debut']},
        ),
        migrations.RenameField(
            model_name='archiveincident',
            old_name='nombre_incidents',
            new_name='compteur',
        ),
        migrations.AlterUniqueTogether(
            name='archiveincident',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='nom_op1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='nom_op2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='nom_op3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op1_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op1_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op2_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op2_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op3_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op3_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.RemoveField(
            model_name='archiveincident',
            name='date',
        ),
    ]
